#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Regenerate the JT-MIDI-007 / JT-PCM-008 run log table in
playback_stall_wedge.md from tests/hw/results/*/*/run.json.

Run after any new run of either case lands, to keep the run log current
without hand-editing it:

    python3 re/wedge_run_log.py

Read-only against tests/hw/results/. Rewrites playback_stall_wedge.md only
between the RUN-LOG markers; everything else in the file is left alone.

Time-to-stall and bytes-at-stall are recovered from two independent files a
run already writes for other reasons, not from any metric the case itself
reports (JT-MIDI-007's own urb_stall_onset_ms is a completion-gap duration,
not a time-into-the-run):

  - dmesg.txt (shared per run) for the case's own JT-MARK line and the
    first "Playback URB stream stalled" line to land in that case's window,
    which gives time-to-stall as the gap between the two kernel timestamps.
  - cases/<id>-<iter>/stderr.txt for the case's own periodic progress
    reports ("Ns  Nbytes  Nbursts"), interpolated at that elapsed time to
    get bytes-at-stall. Only JT-MIDI-007 writes these; JT-PCM-008 has none,
    so its bytes-at-stall is always "unknown" even if it ever stalls.
"""
import glob
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)
HW_DIR = os.path.join(REPO_ROOT, "tests", "hw")
RESULTS_GLOB = os.path.join(HW_DIR, "results", "*", "*", "run.json")
DOC_PATH = os.path.join(HERE, "playback_stall_wedge.md")

sys.path.insert(0, HW_DIR)
from ledger import driver_rev  # noqa: E402  -- same "-dirty means the driver,
                               # not the whole repo" logic ledger.py's matrix
                               # already relies on; don't duplicate it here.

CASE_IDS = ("JT-MIDI-007", "JT-PCM-008")
CEILING_BPS = 3125  # jockey3_get_next_midi_out_byte()'s leaky-bucket limit

BEGIN = "<!-- RUN-LOG:BEGIN (generated by wedge_run_log.py -- do not hand-edit) -->"
END = "<!-- RUN-LOG:END -->"

MARK_RE = re.compile(r"\[\s*(\d+\.\d+)\]\s+JT-MARK (\S+)")
ONSET_RE = re.compile(
    r"\[\s*(\d+\.\d+)\].*Playback URB stream stalled: no completion for (\d+) ms")
PROGRESS_RE = re.compile(r"(\d+)s\s+(\d+) bytes\s+(\d+) bursts")


def load_runs():
    for path in sorted(glob.glob(RESULTS_GLOB)):
        try:
            with open(path, encoding="utf-8") as f:
                run = json.load(f)
        except (OSError, ValueError):
            # A run still in flight has no run.json yet, or a truncated one
            # mid-write; skip it, the next invocation picks it up once done.
            continue
        run["_dir"] = os.path.dirname(path)
        yield run


def driver_label(run):
    build = ((run.get("env") or {}).get("driver") or {}).get("build") or {}
    return driver_rev(build) or "unknown"


def stall_window(dmesg_text, case_id, iteration):
    """(mark_ts, onset_ts) for the first playback stall onset inside this
    case's own JT-MARK window, or None if there isn't one."""
    tag = f"{case_id}#{iteration}"
    lines = dmesg_text.splitlines()
    mark_ts = None
    window_end = None
    for i, line in enumerate(lines):
        m = MARK_RE.search(line)
        if m and m.group(2) == tag:
            mark_ts = float(m.group(1))
            for later in lines[i + 1:]:
                m2 = MARK_RE.search(later)
                if m2:
                    window_end = float(m2.group(1))
                    break
            break
    if mark_ts is None:
        return None
    for line in lines:
        m = ONSET_RE.search(line)
        if not m:
            continue
        ts = float(m.group(1))
        if ts < mark_ts:
            continue
        if window_end is not None and ts >= window_end:
            break
        return mark_ts, ts
    return None


def bytes_at(elapsed_s, stderr_text):
    """Interpolate bytes_sent at elapsed_s from a case's own progress log,
    or None if it has none (JT-PCM-008) or nothing usable landed yet."""
    points = sorted((float(a), int(b))
                    for a, b, _c in (m.groups()
                                     for m in PROGRESS_RE.finditer(stderr_text)))
    if not points:
        return None
    if elapsed_s <= points[0][0]:
        return points[0][1]
    for (t0, b0), (t1, b1) in zip(points, points[1:]):
        if t0 <= elapsed_s <= t1:
            if t1 == t0:
                return b1
            frac = (elapsed_s - t0) / (t1 - t0)
            return round(b0 + frac * (b1 - b0))
    return points[-1][1]


def target_rate(case_id, params):
    if case_id == "JT-MIDI-007":
        return CEILING_BPS * float(params.get("load_fraction", 0.9))
    return 0.0  # JT-PCM-008: no MIDI traffic at all


def row_for(run, result):
    case_id = result["id"]
    iteration = result.get("iteration", 1)
    params = result.get("params") or {}
    metrics = result.get("metrics") or {}
    case_dir = os.path.join(run["_dir"], "cases", f"{case_id}-{iteration}")

    planned = params.get("duration_seconds")
    if planned is None and "hours" in params:
        planned = float(params["hours"]) * 3600
    actual = result.get("duration_s")

    # A bare status=="fail" is not evidence of this wedge -- a case fails
    # for xruns, timeouts, refused rates, anything. Only trust the case's
    # own urb_stalls_playback metric (JT-MIDI-007) or an actual playback
    # stall onset line landing inside this case's dmesg window (checked for
    # every case, since JT-PCM-008 has no such metric of its own to trust).
    try:
        with open(os.path.join(run["_dir"], "dmesg.txt"), encoding="utf-8") as f:
            dmesg_text = f.read()
    except OSError:
        dmesg_text = ""
    window = stall_window(dmesg_text, case_id, iteration)

    stalled = bool(metrics.get("urb_stalls_playback")) or window is not None

    time_to_stall = bytes_at_stall = None
    if window:
        mark_ts, onset_ts = window
        time_to_stall = onset_ts - mark_ts
        try:
            with open(os.path.join(case_dir, "stderr.txt"), encoding="utf-8") as f:
                stderr_text = f.read()
        except OSError:
            stderr_text = ""
        bytes_at_stall = bytes_at(time_to_stall, stderr_text)

    return {
        "date": (run.get("started") or "")[:10],
        "target": run.get("target", "?"),
        "case": case_id,
        "run_id": run.get("run_id") or os.path.basename(run["_dir"]),
        "driver": driver_label(run),
        "target_rate": target_rate(case_id, params),
        "achieved_rate": metrics.get("achieved_bps"),
        "planned_s": planned,
        "actual_s": actual,
        "stalled": stalled,
        "time_to_stall": time_to_stall,
        "bytes_at_stall": bytes_at_stall,
    }


def fmt_rate(v):
    if v is None:
        return "n/a"
    if v == 0:
        return "no MIDI (0 B/s)"
    return f"{v:.0f} B/s"


def fmt_duration(v):
    if v is None:
        return "?"
    if v >= 3600:
        return f"{v / 3600:.1f}h"
    return f"{v:.0f}s"


def fmt_actual_duration(actual, planned):
    """How long the run actually watched the device, which is what a "no
    stall" result's weight rests on -- a case cut short by an unrelated
    failure (a timeout kill, an xrun) proves far less than one that ran its
    planned duration in full, even though both show the same planned value.
    """
    if actual is None:
        return f"{fmt_duration(planned)} planned, never completed"
    label = fmt_duration(actual)
    if planned is not None and actual < planned * 0.95:
        label += f" (cut short -- planned {fmt_duration(planned)})"
    return label


def render_table(rows):
    head = ("| Date | Target | Case | Driver | Target rate | Achieved rate | "
           "Duration | Stall? | Time to stall | Bytes at stall |")
    sep = "|" + "---|" * 10
    lines = [head, sep]
    for r in rows:
        stall_cell = "**yes**" if r["stalled"] else "no"
        if not r["stalled"]:
            tts = bas = "-"
        else:
            tts = (f"{r['time_to_stall']:.0f}s"
                  if r["time_to_stall"] is not None else "unknown")
            bas = (f"{r['bytes_at_stall']:,} bytes"
                  if r["bytes_at_stall"] is not None else "unknown")
        lines.append(
            f"| {r['date']} | {r['target']} | {r['case']} (`{r['run_id']}`) "
            f"| `{r['driver']}` | {fmt_rate(r['target_rate'])} | "
            f"{fmt_rate(r['achieved_rate'])} | "
            f"{fmt_actual_duration(r['actual_s'], r['planned_s'])} | "
            f"{stall_cell} | {tts} | {bas} |")
    return "\n".join(lines)


def main():
    rows = []
    for run in load_runs():
        for result in run.get("results", []):
            if result["id"] in CASE_IDS and result.get("status") in ("pass", "fail"):
                rows.append(row_for(run, result))
    rows.sort(key=lambda r: (r["date"], r["run_id"]))

    table = render_table(rows)

    with open(DOC_PATH, encoding="utf-8") as f:
        doc = f.read()
    if BEGIN not in doc or END not in doc:
        print(f"error: markers not found in {DOC_PATH}", file=sys.stderr)
        return 1
    pre, rest = doc.split(BEGIN, 1)
    _mid, post = rest.split(END, 1)
    new_doc = pre + BEGIN + "\n\n" + table + "\n\n" + END + post

    if new_doc != doc:
        with open(DOC_PATH, "w", encoding="utf-8") as f:
            f.write(new_doc)
        print(f"updated {DOC_PATH} ({len(rows)} rows)")
    else:
        print(f"{DOC_PATH} already up to date ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
